language: python
sudo: false
python: 3.5
env:
  - TOX_ENV=py27-django1.8.X-djangocelery3.1.X-celery3.1.X
  - TOX_ENV=py27-django1.11.X-djangocelery3.1.X-celery3.1.X
  - TOX_ENV=py27-django1.8.X-celery3.1.X
  - TOX_ENV=py27-django1.8.X-celery4.1.X
  - TOX_ENV=py27-django1.11.X-celery3.1.X
  - TOX_ENV=py27-django1.11.X-celery4.1.X
  - TOX_ENV=py35-django1.11.X-celery3.1.X
  - TOX_ENV=py35-django1.11.X-celery4.1.X
  - TOX_ENV=flake8
install: pip install tox
script: tox -e $TOX_ENV
